### ISSUE TITLE
コメントを記述する

### ISSUE THREAD

**Issue by watemo** [engineer-achan/spring-1022#1]
自分が書いたコードでも3日経てば忘れてしまうことが往々にして発生します。
未来の自分のためにも、このコードを読む他の人のためにもしっかりと、しかし簡潔に
下記のコメントを記述するようにしましょう。

- クラス
- メソッド
- プロパティ

個人的にはクラスコメントにauthor（作成者）を絶対に書いてほしいです。
芸術家や伝統工芸家が自分の作品に名前を入れるように
責任をもってこのコードを書いた、ということを忘れないためにも名前を書きましょう。

書き方の例は下記が参考になるかと思います。
https://style.potepan.com/articles/15252.html#Javadoc-2

**Comment by engineer-achan** [comment]
> 自分が書いたコードでも3日経てば忘れてしまうことが往々にして発生します。
> 未来の自分のためにも、このコードを読む他の人のためにもしっかりと、しかし簡潔に
> 下記のコメントを記述するようにしましょう。
> 
> * クラス
> * メソッド
> * プロパティ
> 
> 個人的にはクラスコメントにauthor（作成者）を絶対に書いてほしいです。
> 芸術家や伝統工芸家が自分の作品に名前を入れるように
> 責任をもってこのコードを書いた、ということを忘れないためにも名前を書きましょう。
> 
> 書き方の例は下記が参考になるかと思います。
> https://style.potepan.com/articles/15252.html#Javadoc-2

ありがとうございます
対応します

**Comment by engineer-achan** [comment]
閉じます
