### ISSUE TITLE
SpringDataRestをやめてコントローラクラスでPOSTGETできるようにしました

### ISSUE THREAD

**Issue by engineer-achan** [engineer-achan/spring-1022#11]

**Comment by engineer-achan** [comment]
タイトルにもある通りSpringDataRestをやめてコントローラクラスでPOSTGETできるようにしました。
現在は
・http://localhost:8080/allmessagesで全権取得
・http://localhost:8080/allmessages/{id}で個別取得
・http://localhost:8080/postmessageで新規投稿
ができます。

質問です。
以前のお話ですとコントローラ→サービス
の流れだったはずですがサービスクラスをうまく使えませんでした。
自分の中でコントローラとサービスの役割の違い、両方同時に必要な理由がはっきりわかっていません。

なので
・コントローラとサービスの役割の違い
コントローラとサービス両方がいる理由
・コントローラとサービスの繋げ方

を教えて欲しいです！！

**Comment by engineer-achan** [comment]
追記：コントローラクラスとサービスクラスを分けてpost,getできてます！
ただ分ける意味については深くは理解できていないです

**Comment by watemo** [comment]
> ・コントローラとサービスの役割の違い
> ・コントローラとサービス両方がいる理由
> ・コンポーネントを使う時、使わない時の違い

文章で書こうと思うと端的にまとめられませんでしたので、
後日、口頭などで説明させてください。
その時の資料用にURLを貼っておきます。

https://system.blog.uuum.jp/entry/using-service-class

https://www.baeldung.com/spring-component-repository-service

**Comment by engineer-achan** [comment]
> 後日、口頭などで説明させてください。
> その時の資料用にURLを貼っておきます。
> 
> https://system.blog.uuum.jp/entry/using-service-class
> 
> https://www.baeldung.com/spring-component-repository-service

おつかれさまです
全然大丈夫です。貴重なお休みなのにわざわざ返信してくださりありがとうございます。。
資料用URL確認しておきます！
