### ISSUE TITLE
Exception実装でこけました

### ISSUE THREAD

**Issue by engineer-achan** [engineer-achan/spring-1022#12]
**バリデーションはうまくできたしExceptionも実装するぞー！と思っていた矢先こけました。**

現状は存在しないidで更新・削除しようとすると「200 NoConnect」になります。
動かないのでマスターブランチではなく、Practiceブランチにプッシュしています。

よく理解できていない点

1. if (!message.isPresent()) {
			throw new NotFoundException(id);
		}
引数がidはおかしいですか？

2. NotFoundException.javaとExceptionHandle.javaの関係性、処理の流れがうまくイメージできていません。

おそらく見ていて不可解な点があると思いますので（バリデーションも僕ができたと思っているだけでよくない記述かもしれない）ご指摘していただけると嬉しいです。

**Comment by watemo** [comment]
Exception周りの実装に対しては下記のコミットに
コメントを追加しておりますのでご確認をお願い致します。

https://github.com/engineer-achan/spring-1022/commit/7ed7f6b19864d181cfb78e3117c37c5ebbec239b



> 1. if (!message.isPresent()) {
> throw new NotFoundException(id);
> }
> 引数がidはおかしいですか？

Java標準のExceptionの実装等を確認してもらえれば分かると思いますが、
一般的にはエラーメッセージの文字列(String)を引数として受け取ることが多いです。

ただ、
『エラーメッセージは自作のExceptionクラスの中で生成するので、引数にはパラメータだけを受け取る』
という実装もありますので、仕様やその時やりたい事に応じて作成するべきだと思います。

とりあえず今回は標準のExceptionに則ってStringを受け取るようにしてみましょう。


> 2. NotFoundException.javaとExceptionHandle.javaの関係性、処理の流れがうまくイメージできていません。

こちらはまた実際のソースを一緒に確認しながら説明させてください。

**Comment by engineer-achan** [comment]
解決したので閉じます
