### ISSUE TITLE
Practice_20191114ブランチが壊れている？

### ISSUE THREAD

**Issue by watemo** [engineer-achan/spring-1022#14]
下記のブランチが壊れているのか、チェックアウトが出来ない状態です。

https://github.com/engineer-achan/spring-1022/tree/Practice_20191114

プロジェクト内に”spring-1022”ディレクトリがあり、
意図した状態ではないと思いますので、ご確認をお願い致します。

**Comment by engineer-achan** [comment]
承知いたしました

**Comment by watemo** [comment]
チェックアウトできることを確認しましたのでクローズします。
