### ISSUE TITLE
コードのインデントを揃える

### ISSUE THREAD

**Issue by watemo** [engineer-achan/spring-1022#2]
クラスによって、インデントがタブだったりスペースだったりしていますので、
プロジェクト内では全て統一するようにしましょう。
（個人的にはスペース４つ派ですが、ここは個人の好みですので…）

インデントが揃っていない、タブとスペースが混在している、という状態は可読性が低く
後々読む人を困らせてしまいます。

IDEには大体フォーマッターがついていますので、
自動で整形してくれるように設定しておくと楽です。

・Visual Studio Codeの自動整形機能
https://qiita.com/syo_nasu/items/e03cbcd09c5aba23e92e

・Eclipseのフォーマッター
https://qiita.com/koma01102003/items/2167ca798f7dc4c4b278

**Comment by engineer-achan** [comment]
> クラスによって、インデントがタブだったりスペースだったりしていますので、
> プロジェクト内では全て統一するようにしましょう。
> （個人的にはスペース４つ派ですが、ここは個人の好みですので…）
> 
> インデントが揃っていない、タブとスペースが混在している、という状態は可読性が低く
> 後々読む人を困らせてしまいます。
> 
> IDEには大体フォーマッターがついていますので、
> 自動で整形してくれるように設定しておくと楽です。
> 
> ・Visual Studio Codeの自動整形機能
> https://qiita.com/syo_nasu/items/e03cbcd09c5aba23e92e
> 
> ・Eclipseのフォーマッター
> https://qiita.com/koma01102003/items/2167ca798f7dc4c4b278

確かに今までは自分で作るだけだったのであまり意識していませんでした。。
可読性に着目して修正してみます

**Comment by engineer-achan** [comment]
Eclipse自動整形
https://qiita.com/jabaraster/items/96a61e768b3d51909166

**Comment by engineer-achan** [comment]
解決したので閉じます
