### ISSUE TITLE
Lombokを導入する

### ISSUE THREAD

**Issue by watemo** [engineer-achan/spring-1022#3]
データを保持するMessageクラスにgetter/setterがありますが、
Lombok を使うとgetter/setterの記述そのものが不要になるのでオススメです。

JavaのWebアプリではよく使われるライブラリなので
使い方を覚えておいて損はないと思います。

コード量が減る＝バグの発生率が下がる、なので
こういった便利なライブラリは積極的に使っていきましょう。
（実際の案件で使えるか、はまた別なのですが…）

・Lombok 使い方メモ
https://qiita.com/opengl-8080/items/671ffd4bf84fe5e32557

**Comment by engineer-achan** [comment]
> データを保持するMessageクラスにgetter/setterがありますが、
> Lombok を使うとgetter/setterの記述そのものが不要になるのでオススメです。
> 
> JavaのWebアプリではよく使われるライブラリなので
> 使い方を覚えておいて損はないと思います。
> 
> コード量が減る＝バグの発生率が下がる、なので
> こういった便利なライブラリは積極的に使っていきましょう。
> （実際の案件で使えるか、はまた別なのですが…）
> 
> ・Lombok 使い方メモ
> https://qiita.com/opengl-8080/items/671ffd4bf84fe5e32557

他のプロジェクトを作っていた時使ったことあります！（なんで今回使わないんだよという感じですが使いませんでした）
便利ですよね。使ってるバージョンにして動かしてみます
参考リンク有難うございます

**Comment by watemo** [comment]
Lombok導入済みのため、本件をクローズします。
