### ISSUE TITLE
エラーハンドリング（例外処理）を追加する

### ISSUE THREAD

**Issue by watemo** [engineer-achan/spring-1022#4]
エラーが発生した際の挙動が考慮されていないので例外処理を追加しましょう。

DB接続エラーなど正常に動作しなかった場合、現在は
　HTTPステータスコード：200
　レスポンス：NO CONTENT
が返ってきていますが、
HTTPステータスコードの200は『正しいレスポンスが返ってきた』という意味になるので
エラー時のコードとしては相応しくありません。

よくあるパターンとしては下記のようになります。
　正常：200
　ユーザの入力不正：400
　サーバ内部でのエラー：500

HTTPステータスコードの意味は下記にまとまっていますので良ければ参考にしてください。

・RESTful API設計におけるHTTPステータスコードの指針
https://qiita.com/uenosy/items/ba9dbc70781bddc4a491

また、レスポンスもNO CONTENTではなく、
エラーメッセージや、アプリ内のエラーコードを返すというのがよくあるパターンです。
下記に有名サービスのエラーレスポンスがまとまっていますので、こちらも参考にしてみてください。

・WebAPIでエラーをどう表現すべき？15のサービスを調査してみた
https://qiita.com/suin/items/f7ac4de914e9f3f35884

**Comment by engineer-achan** [comment]
> エラーが発生した際の挙動が考慮されていないので例外処理を追加しましょう。
> 
> DB接続エラーなど正常に動作しなかった場合、現在は
> 　HTTPステータスコード：200
> 　レスポンス：NO CONTENT
> が返ってきていますが、
> HTTPステータスコードの200は『正しいレスポンスが返ってきた』という意味になるので
> エラー時のコードとしては相応しくありません。
> 
> よくあるパターンとしては下記のようになります。
> 　正常：200
> 　ユーザの入力不正：400
> 　サーバ内部でのエラー：500
> 
> HTTPステータスコードの意味は下記にまとまっていますので良ければ参考にしてください。
> 
> ・RESTful API設計におけるHTTPステータスコードの指針
> https://qiita.com/uenosy/items/ba9dbc70781bddc4a491
> 
> また、レスポンスもNO CONTENTではなく、
> エラーメッセージや、アプリ内のエラーコードを返すというのがよくあるパターンです。
> 下記に有名サービスのエラーレスポンスがまとまっていますので、こちらも参考にしてみてください。
> 
> ・WebAPIでエラーをどう表現すべき？15のサービスを調査してみた
> https://qiita.com/suin/items/f7ac4de914e9f3f35884

この辺は意識したことなかったですね、、、
勉強しながら修正します
有難うございます

**Comment by engineer-achan** [comment]
> > エラーが発生した際の挙動が考慮されていないので例外処理を追加しましょう。
> > DB接続エラーなど正常に動作しなかった場合、現在は
> > 　HTTPステータスコード：200
> > 　レスポンス：NO CONTENT
> > が返ってきていますが、
> > HTTPステータスコードの200は『正しいレスポンスが返ってきた』という意味になるので
> > エラー時のコードとしては相応しくありません。
> > よくあるパターンとしては下記のようになります。
> > 　正常：200
> > 　ユーザの入力不正：400
> > 　サーバ内部でのエラー：500
> > HTTPステータスコードの意味は下記にまとまっていますので良ければ参考にしてください。
> > ・RESTful API設計におけるHTTPステータスコードの指針
> > https://qiita.com/uenosy/items/ba9dbc70781bddc4a491
> > また、レスポンスもNO CONTENTではなく、
> > エラーメッセージや、アプリ内のエラーコードを返すというのがよくあるパターンです。
> > 下記に有名サービスのエラーレスポンスがまとまっていますので、こちらも参考にしてみてください。
> > ・WebAPIでエラーをどう表現すべき？15のサービスを調査してみた
> > https://qiita.com/suin/items/f7ac4de914e9f3f35884
> 
> この辺は意識したことなかったですね、、、
> 勉強しながら修正します
> 有難うございます

今回ですとRequestFilter.javaに書いていくという認識でよろしいでしょうか？

**Comment by watemo** [comment]
Springには例外ハンドリング用のクラスを作成できる仕組みがあるので
そちらを使ってみましょう。

・SpringBootの@RestControllerで例外処理をする
https://qiita.com/shotana/items/f3627e45feb912946c7c

上記のページでは@RestControllerの例が載っていますが、Spring Data RESTも同様に実装可能です。


org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler
を継承したクラスを作成し、そのクラスに"@ControllerAdvice"を付けます。
クラス内には@ExceptionHandlerアノテーションでエラーの種類を定義し、
エラーに応じたレスポンスを作成するメソッドを追加していきます。


■実装例
~~~
/**
 * エラーレスポンス用のモデルクラス
 * 
 * @author （自分の名前）
 */
@Data
public ErrorResponse {

    /**
     * エラーメッセージ
     */
    private String message;
    
    /**
     * エラーコード<br>
     * 1：入力値エラー<br>
     * 2：XXXエラー<br>
     * 3：XXXエラー<br>
     * 9：システムエラー<br>
     */
    private int resultCode;
}
~~~

~~~
/**
 * 例外ハンドラクラス
 * 
 * @author （自分の名前）
 */
@ControllerAdvice
public class ApiExceptionHandler extends ResponseEntityExceptionHandler {

    /**
     * エラー発生時、クライアント用のエラーレスポンスを作成する
     */
    @Override
    protected ResponseEntity<Object> handleExceptionInternal(Exception ex, Object body, HttpHeaders headers,
            HttpStatus status, WebRequest request) {
        
        //エラーレスポンスの作成処理
        ErrorResponse errorRes = new ErrorResponse();
        errorRes.setMessage("エラーが発生しました");//メッセージをコード内に直接記述はよろしくないのですが説明のために利用しています。真似をしてはいけません…。
        errorRes.setResultCode(9);//本来は、ここのエラーコードも定数や設定ファイルに定義しておくのが正しいです
        return super.handleExceptionInternal(ex, errorRes, headers, HttpStatus.INTERNAL_SERVER_ERROR, request);
    }

    /**
     * リクエストパラメータ不正時、クライアント用のエラーレスポンスを作成する
     *
     * @param ex Exceptionオブジェクト
     * @param request リクエスト
     * @return エラーレスポンス
     */
    @ExceptionHandler(BadRequestException.class)
    protected ResponseEntity<Object> handleBadRequestException(BadRequestException ex, WebRequest request) {
        ErrorResponse errorRes = new ErrorResponse();
        errorRes.setMessage("エラーが発生しました");
        errorRes.setResultCode(1);
        return super.handleExceptionInternal(ex, errorRes, new HttpHeaders(), HttpStatus.BAD_REQUEST, request);
    }
    
    //その他、必要なエラー処理があればメソッドを追加する。

}
~~~

上記の処理を実装し、MongoDBが起動していない状態でAPIリクエストを行うと、エラーレスポンスが返ってくると思います。
試してみてください。
（動かない場合は、私の記述が間違っている場合もあります。その時は教えてください）

**Comment by engineer-achan** [comment]
> Springには例外ハンドリング用のクラスを作成できる仕組みがあるので
> そちらを使ってみましょう。
> 
> ・SpringBootの@RestControllerで例外処理をする
> https://qiita.com/shotana/items/f3627e45feb912946c7c
> 
> 上記のページでは@RestControllerの例が載っていますが、Spring Data RESTも同様に実装可能です。
> 
> org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler
> を継承したクラスを作成し、そのクラスに"@ControllerAdvice"を付けます。
> クラス内には@ExceptionHandlerアノテーションでエラーの種類を定義し、
> エラーに応じたレスポンスを作成するメソッドを追加していきます。
> 
> ■実装例
> 
> ```
> /**
>  * エラーレスポンス用のモデルクラス
>  * 
>  * @author （自分の名前）
>  */
> @Data
> public ErrorResponse {
> 
>     /**
>      * エラーメッセージ
>      */
>     private String message;
>     
>     /**
>      * エラーコード<br>
>      * 1：入力値エラー<br>
>      * 2：XXXエラー<br>
>      * 3：XXXエラー<br>
>      * 9：システムエラー<br>
>      */
>     private int resultCode;
> }
> ```
> 
> ```
> /**
>  * 例外ハンドラクラス
>  * 
>  * @author （自分の名前）
>  */
> @ControllerAdvice
> public class ApiExceptionHandler extends ResponseEntityExceptionHandler {
> 
>     /**
>      * エラー発生時、クライアント用のエラーレスポンスを作成する
>      */
>     @Override
>     protected ResponseEntity<Object> handleExceptionInternal(Exception ex, Object body, HttpHeaders headers,
>             HttpStatus status, WebRequest request) {
>         
>         //エラーレスポンスの作成処理
>         ErrorResponse errorRes = new ErrorResponse();
>         errorRes.setMessage("エラーが発生しました");//メッセージをコード内に直接記述はよろしくないのですが説明のために利用しています。真似をしてはいけません…。
>         errorRes.setResultCode(9);//本来は、ここのエラーコードも定数や設定ファイルに定義しておくのが正しいです
>         return super.handleExceptionInternal(ex, errorRes, headers, HttpStatus.INTERNAL_SERVER_ERROR, request);
>     }
> 
>     /**
>      * リクエストパラメータ不正時、クライアント用のエラーレスポンスを作成する
>      *
>      * @param ex Exceptionオブジェクト
>      * @param request リクエスト
>      * @return エラーレスポンス
>      */
>     @ExceptionHandler(BadRequestException.class)
>     protected ResponseEntity<Object> handleBadRequestException(BadRequestException ex, WebRequest request) {
>         ErrorResponse errorRes = new ErrorResponse();
>         errorRes.setMessage("エラーが発生しました");
>         errorRes.setResultCode(1);
>         return super.handleExceptionInternal(ex, errorRes, new HttpHeaders(), HttpStatus.BAD_REQUEST, request);
>     }
>     
>     //その他、必要なエラー処理があればメソッドを追加する。
> 
> }
> ```
> 
> 上記の処理を実装し、MongoDBが起動していない状態でAPIリクエストを行うと、エラーレスポンスが返ってくると思います。
> 試してみてください。
> （動かない場合は、私の記述が間違っている場合もあります。その時は教えてください）

ありがとうございます。
実装してみます

**Comment by engineer-achan** [comment]
質問です。
自作の例外処理（404対策）についてです。
現在はGlobalExceptionHandlerとNotFoundExceptionとErrorResponseの3つのクラスで処理しています。
「ErrorResponse」はエラーレスポンス用のモデルクラスと認識していますが実際のクラスの役割がイメージできていません。
「メッセージの格納」と言葉上ではわかっていますが具体的な処理の流れが掴めていません。

今までモデルクラスはデータベースに対して参照するためのクラスとして使ったことしかなかったので今回理解しにくいと感じています。。（今回のMessageのような）

処理の流れとともに、エラーレスポンスクラスの役割を今一度説明してくださると嬉しいです。

うまく伝わらない場合は僕の説明が下手だと思うので「よくわからんぞ！」と遠慮なくおっしゃってください。
時間があるときに確認してくださればと思います。

**Comment by engineer-achan** [comment]
分かりやすかったです。ありがとうございました
