### ISSUE TITLE
バリデーション（入力値チェック）を追加する

### ISSUE THREAD

**Issue by watemo** [engineer-achan/spring-1022#5]
APIの場合、正しいパラメータが必ず送られてくる、という保証はありません。
むしろ世の中には悪いハッカーがたくさんおりますので、
実装者が思いもつかないパラメータをバンバン送り付けてくる状況がよくあります。
（SQLインジェクションとかが有名ですね）

というわけで自衛しましょう。
APIパラメータのバリデーションは必須です。

よくあるバリデーションは下記です。

- nullを認めるか、認めないか
- 型が間違っていないか（数値が入るパラメータに文字列が入っている等）
- 数値は範囲に収まっているか（マイナス値は弾く等）
- サイズは範囲に収まっているか（文字数の上限等）
- 不正な形式ではないか（URLを登録する項目に日本語が入っている等）

これ以外にもアプリ仕様に則ったチェックなどがあります。
今回のアプリではどのようなチェックが必要か一旦、リストアップしてみましょう。

**Comment by engineer-achan** [comment]
> APIの場合、正しいパラメータが必ず送られてくる、という保証はありません。
> むしろ世の中には悪いハッカーがたくさんおりますので、
> 実装者が思いもつかないパラメータをバンバン送り付けてくる状況がよくあります。
> （SQLインジェクションとかが有名ですね）
> 
> というわけで自衛しましょう。
> APIパラメータのバリデーションは必須です。
> 
> よくあるバリデーションは下記です。
> 
> * nullを認めるか、認めないか
> * 型が間違っていないか（数値が入るパラメータに文字列が入っている等）
> * 数値は範囲に収まっているか（マイナス値は弾く等）
> * サイズは範囲に収まっているか（文字数の上限等）
> * 不正な形式ではないか（URLを登録する項目に日本語が入っている等）
> 
> これ以外にもアプリ仕様に則ったチェックなどがあります。
> 今回のアプリではどのようなチェックが必要か一旦、リストアップしてみましょう。

メッセージ確認しております。
リストアップ、実装をとりあえず順を追ってやってみます

**Comment by engineer-achan** [comment]
> APIの場合、正しいパラメータが必ず送られてくる、という保証はありません。
> むしろ世の中には悪いハッカーがたくさんおりますので、
> 実装者が思いもつかないパラメータをバンバン送り付けてくる状況がよくあります。
> （SQLインジェクションとかが有名ですね）
> 
> というわけで自衛しましょう。
> APIパラメータのバリデーションは必須です。
> 
> よくあるバリデーションは下記です。
> 
> * nullを認めるか、認めないか
> * 型が間違っていないか（数値が入るパラメータに文字列が入っている等）
> * 数値は範囲に収まっているか（マイナス値は弾く等）
> * サイズは範囲に収まっているか（文字数の上限等）
> * 不正な形式ではないか（URLを登録する項目に日本語が入っている等）
> 
> これ以外にもアプリ仕様に則ったチェックなどがあります。
> 今回のアプリではどのようなチェックが必要か一旦、リストアップしてみましょう。

今回ですと現段階では文字数制限をかけてみたいですが、Vueの方で制限するイメージであっていますでしょうか

**Comment by watemo** [comment]
バリデーションはクライアント側、サーバ側の両方で行うというのが一般的です。

仰るようにVue側で文字数制限をすると
　画面側で文字数チェック
　↓
　画面にエラーメッセージを表示（ユーザ名は100文字以内で入力してください、など）
となり、APIにリクエストが飛んできません。
API呼び出し回数が抑えられてとてもGoodです。

しかし、公開されているAPIは下記のようなツールを使う事でこちらが作成した画面以外からも呼ぶことが可能です。

・API開発・テスト便利ツール Postmanの使い方メモ
https://qiita.com/zaburo/items/16ac4189d0d1c35e26d1

そういった場合、画面を経由しない為Vue側のチェックをスルーしてしまいます。
本来は100文字しか入力してほしくないユーザ名に、200文字のパラメータを送られるという事が起こりえます。

APIは可能な限り、どんな無茶苦茶なパラメータでリクエストされてもデータやシステムが壊れないないように作る、というのが鉄則です。
また、クライアント側でのバリデーションには限度があるので（DB内のデータ相関チェックなどは出来ない）、
基本的にはサーバ側で可能な限り厳密なチェックを行うようにしましょう。


Springには基本的なバリデーションをアノテーションで設定できるとても便利な機能があります。
まずはこちらを利用してみましょう。

・Spring標準の制約アノテーション一覧
https://terasolunaorg.github.io/guideline/public_review/ArchitectureInDetail/Validation.html#jsr-303



手順としてはまずAPIがリクエストされた際にバリデーションを実施するとアプリに設定する必要があります。
下記のクラスを新規に作成してください。

~~~
@Configuration
public class RestConfig implements RepositoryRestConfigurer {

    @Autowired
    private Validator validator;

    @Override
    public void configureValidatingRepositoryEventListener(ValidatingRepositoryEventListener validatingListener) {
        validatingListener.addValidator("beforeCreate", validator);
        validatingListener.addValidator("beforeSave", validator);
    }
}
~~~

次に、Messageクラスのプロパティに制約アノテーションを追加します。

例）usernameを必須、かつ100文字以内にする場合
~~~
    @NotNull
    @Size(max = 100)
    private String username;
~~~

全て完了した状態でSpringアプリを起動し、
　ユーザ名を空で送信
　ユーザ名に101文字以上を入力して送信
をそれぞれ試してみてください。
400エラーとなり、登録されないはずです。

（Vue側のバリデーションはまた別途）

**Comment by engineer-achan** [comment]
> バリデーションはクライアント側、サーバ側の両方で行うというのが一般的です。
> 
> 仰るようにVue側で文字数制限をすると
> 　画面側で文字数チェック
> 　↓
> 　画面にエラーメッセージを表示（ユーザ名は100文字以内で入力してください、など）
> となり、APIにリクエストが飛んできません。
> API呼び出し回数が抑えられてとてもGoodです。
> 
> しかし、公開されているAPIは下記のようなツールを使う事でこちらが作成した画面以外からも呼ぶことが可能です。
> 
> ・API開発・テスト便利ツール Postmanの使い方メモ
> https://qiita.com/zaburo/items/16ac4189d0d1c35e26d1
> 
> そういった場合、画面を経由しない為Vue側のチェックをスルーしてしまいます。
> 本来は100文字しか入力してほしくないユーザ名に、200文字のパラメータを送られるという事が起こりえます。
> 
> APIは可能な限り、どんな無茶苦茶なパラメータでリクエストされてもデータやシステムが壊れないないように作る、というのが鉄則です。
> また、クライアント側でのバリデーションには限度があるので（DB内のデータ相関チェックなどは出来ない）、
> 基本的にはサーバ側で可能な限り厳密なチェックを行うようにしましょう。
> 
> Springには基本的なバリデーションをアノテーションで設定できるとても便利な機能があります。
> まずはこちらを利用してみましょう。
> 
> ・Spring標準の制約アノテーション一覧
> https://terasolunaorg.github.io/guideline/public_review/ArchitectureInDetail/Validation.html#jsr-303
> 
> 手順としてはまずAPIがリクエストされた際にバリデーションを実施するとアプリに設定する必要があります。
> 下記のクラスを新規に作成してください。
> 
> ```
> @Configuration
> public class RestConfig implements RepositoryRestConfigurer {
> 
>     @Autowired
>     private Validator validator;
> 
>     @Override
>     public void configureValidatingRepositoryEventListener(ValidatingRepositoryEventListener validatingListener) {
>         validatingListener.addValidator("beforeCreate", validator);
>         validatingListener.addValidator("beforeSave", validator);
>     }
> }
> ```
> 
> 次に、Messageクラスのプロパティに制約アノテーションを追加します。
> 
> 例）usernameを必須、かつ100文字以内にする場合
> 
> ```
>     @NotNull
>     @Size(max = 100)
>     private String username;
> ```
> 
> 全て完了した状態でSpringアプリを起動し、
> 　ユーザ名を空で送信
> 　ユーザ名に101文字以上を入力して送信
> をそれぞれ試してみてください。
> 400エラーとなり、登録されないはずです。
> 
> （Vue側のバリデーションはまた別途）

なるほどです。
クライアント側、サーバ側の両方で行うのですね！
こちらもやってみます

**Comment by watemo** [comment]
すみません。上記のコード例に不足がありました。

1. アプリに対してValidatorを使うように設定する
2. Modelクラス(今回はMessage)に制約アノテーションを追加する
3. Modelクラスをパラメータとして受け取るメソッドを定義する（←ここを記述していない）

今は制約アノテーションを追加したModelクラスが
リクエストパラメータとして利用されていないため、入力値チェックが呼ばれていません。

MessageControllerクラスのpostMessageメソッドを下記のように修正してみてください。

~~~
    @PostMapping("/messages")
    public Message postMessage(@PathVariable String messages) {
~~~
↓
~~~
    @PostMapping
    public Message postMessage(@RequestBody @Validated Message message) {
~~~

_※`@PostMapping`のパスを変更した理由はこの話からそれてしまいますので、
　https://github.com/engineer-achan/spring-1022/issues/8 のIssueで説明しますね。_


修正後、"http://localhost:8081/message"に
パラメータが何もない状態でPOSTリクエストを投げてみてください。
下記のようなエラーがIDEのログに表示されればバリデーションが有効になっています。
（このエラーをハンドリングする方法はまた別途）

> ERROR(500) 2019/10/30 18:27:34.693: remoteAddr:0:0:0:0:0:0:0:1, remoteHost:0:0:0:0:0:0:0:1, requestURL:http://localhost:8081/message
> org.springframework.web.bind.MethodArgumentNotValidException: Validation failed for argument [0] in public com.west.entity.Message com.west.controller.MessageController.postMessage(com.west.entity.Message): [Field error in object 'message' on field 'username': rejected value [null]; codes [NotNull.message.username,NotNull.username,NotNull.java.lang.String,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [message.username,username]; arguments []; default message [username]]; default message [must not be null]] 
> 	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.resolveArgument(RequestResponseBodyMethodProcessor.java:138)
> 	at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:127)
> 	at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:167)
> 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:134)
> 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
> 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892)
> 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
> 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
> 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039)
> 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
> 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
> 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
> 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at com.west.config.RequestFilter.doFilter(RequestFilter.java:63)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
> 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
> 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
> 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)
> 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
> 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
> 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
> 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
> 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
> 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
> 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)
> 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)
> 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> 	at java.lang.Thread.run(Thread.java:748)


`@PathVariable`はAPIパスに含まれるパラメータを利用する場合のアノテーションです。
メッセージ登録のようにPOSTメソッドのbodyに含まれるパラメータを利用する場合は
`@RequestBody`を使うようにしましょう。

例）
部署に対して社員情報を登録する下記のようなAPIがあったとします。
http://localhost:8081/employee/{department}/{division}

BP部クラウド課に社員情報を登録する場合のリクエストURLは下記になります。
http://localhost:8081/employee/bp/cloud

下記のJSONのパラメータを送信します。
> 　{
> 　  "employeeNo":”ab12345”,
> 　  "firstName":"Taro",
> 　  "familyName":"Yamada",
> 　  "gender":"male"
> 　}

この場合、"bp"や"cloud"等のパスに含まれるパラメータは`@PathVariable`で、
JSONは`@RequestBody`で受け取ります。

**Comment by watemo** [comment]
Spring Data RESTではない場合、
Restconfigクラス、ValidatingRepositoryEventListenerクラスは不要でした。

SpringBootでは

- モデルクラスに制約用のアノテーション(`@NotEmpty`や`@Size`等)を追加
- コントローラクラスで受け取る引数に`@Validated`アノテーションを追加

とすることでバリデーションが利用可能です。

上記のクラスを削除した状態で、再度チェックに引っ掛かるようなリクエストを
投げて確認してみてください。

**Comment by engineer-achan** [comment]
400Noconnectになりました
えらーを表示させるよう実装します

**Comment by engineer-achan** [comment]
閉じます
