### ISSUE TITLE
プロパティファイルの記述順

### ISSUE THREAD

**Issue by watemo** [engineer-achan/spring-1022#6]
現在下記のように記述されていますが、
カテゴリごとに分けて記述＆コメントを追加しておいた方が見やすいです。

今は設定値の数が少ないので良いのですが後々、数が多くなってくると
項目を探す際に見つけられなくなります。
そして、別々の人が同じ設定値を名前違いで増やしていき、メンテナンスが追い付かなくな…
っているのが今の私のプロジェクトです…（とても悲しい）。

プロパティファイルは先頭に"#"を付けた行がコメント行になるので、
活用していきましょう。

■現在
> spring.data.mongodb.database=example
> server.port=8081
> spring.data.mongodb.username=exa
> spring.data.mongodb.password=exa

■修正後

> #サーバ設定
> server.port=8081
> 
> #DB設定
> spring.data.mongodb.database=example
> spring.data.mongodb.username=exa
> spring.data.mongodb.password=exa

**Comment by engineer-achan** [comment]
> 現在下記のように記述されていますが、
> カテゴリごとに分けて記述＆コメントを追加しておいた方が見やすいです。
> 
> 今は設定値の数が少ないので良いのですが後々、数が多くなってくると
> 項目を探す際に見つけられなくなります。
> そして、別々の人が同じ設定値を名前違いで増やしていき、メンテナンスが追い付かなくな…
> っているのが今の私のプロジェクトです…（とても悲しい）。
> 
> プロパティファイルは先頭に"#"を付けた行がコメント行になるので、
> 活用していきましょう。
> 
> ■現在
> 
> > spring.data.mongodb.database=example
> > server.port=8081
> > spring.data.mongodb.username=exa
> > spring.data.mongodb.password=exa
> 
> ■修正後
> 
> > #サーバ設定
> > server.port=8081
> > #DB設定
> > spring.data.mongodb.database=example
> > spring.data.mongodb.username=exa
> > spring.data.mongodb.password=exa

なるほどです
人のことを考えない記述は悲しいですね
わかりやすい記述を心がけます

**Comment by watemo** [comment]
プロパティファイルへのコメント追加ありがとうございます。

順番が気になったので修正しております。
下記コミットをご確認下さい。
https://github.com/engineer-achan/spring-1022/commit/897991af8ad93719f81c32f3a57fff099d9dc821

カテゴリ別にコメントを付けておくのも、後から修正箇所を探しやすくてオススメです。

**Comment by engineer-achan** [comment]
> カテゴリ別にコメントを付けておくのも、後から修正箇所を探しやすくてオススメです。

ありがとうございます
ためになる読みもの拝見しました
どれも勉強になりましたが特に【関心の分離を意識した名前設計で巨大クラスを爆殺する】は今後も定期的に目を通したいと思う内容でした。

コードを書く際に説明やわかりやすいこめんとをしっかりつけること、混乱を招かない構造を設計する癖をつけていきます

**Comment by engineer-achan** [comment]
閉じます
