### ISSUE TITLE
APIの利用するメソッドのみ公開する

### ISSUE THREAD

**Issue by watemo** [engineer-achan/spring-1022#8]
現在はCRUD全てに対応するメソッド(GET,POST,PUT,PATCH,DELETE,OPTIONS)が
公開されていますが
脆弱性になってしまう可能性がありますので、
利用する想定のないメソッドは公開しない方が良いです。

APIの入り口はなるべく狭く、必要最低限に絞る。
これが基本ポリシーになりますので、覚えておきましょう。

現在のアプリだとGETとPOSTしか使っていませんので、
まずはこの2つのみ公開するように変更してみましょう。

現在実装しているMessageRepositoryはメソッドを指定して非公開にする、
という事が出来ないらしいので、
ここはよくある作りの下記構成に変更してみようと思います。

> Conrtoller→Service→Repository→（MongoDB)

雛形として作成したものをコミットしておりますので、ご確認をお願い致します。
現在は、IDを指定して1件のデータを取得する処理を実装済みです。

ソース中にTODOタグを追加しております通り、まずは試しに

- 全件取得用のGETメソッド
- 新規登録用のPOSTメソッド

を追加してみてください。

実装で詰まってしまったり、「これは何をしているのか？」など不明な点がありましたら、
遠慮なくご連絡くださいね。

**Comment by watemo** [comment]
現在実装済みのAPIは下記のようにリクエストすることで利用可能です

■IDが”5db2832ec592b6151047c318”の場合

・URL
> http://localhost:8081/message/5db2832ec592b6151047c318

・レスポンス
> {
>   "id": "5db2832ec592b6151047c318",
>   "description": "本日は雨天です！",
>   "username": "水口",
>   "date": "2019-10-24T09:55:00.000+0000"
> }

**Comment by engineer-achan** [comment]
> 現在はCRUD全てに対応するメソッド(GET,POST,PUT,PATCH,DELETE,OPTIONS)が
> 公開されていますが
> 脆弱性になってしまう可能性がありますので、
> 利用する想定のないメソッドは公開しない方が良いです。
> 
> APIの入り口はなるべく狭く、必要最低限に絞る。
> これが基本ポリシーになりますので、覚えておきましょう。
> 
> 現在のアプリだとGETとPOSTしか使っていませんので、
> まずはこの2つのみ公開するように変更してみましょう。
> 
> 現在実装しているMessageRepositoryはメソッドを指定して非公開にする、
> という事が出来ないらしいので、
> ここはよくある作りの下記構成に変更してみようと思います。
> 
> > Conrtoller→Service→Repository→（MongoDB)
> 
> 雛形として作成したものをコミットしておりますので、ご確認をお願い致します。
> 現在は、IDを指定して1件のデータを取得する処理を実装済みです。
> 
> ソース中にTODOタグを追加しております通り、まずは試しに
> 
> * 全件取得用のGETメソッド
> * 新規登録用のPOSTメソッド
> 
> を追加してみてください。
> 
> 実装で詰まってしまったり、「これは何をしているのか？」など不明な点がありましたら、
> 遠慮なくご連絡くださいね。

やってみます。
質問点が生じましたらまとめておきます。
丁寧にありがとうございます。心強いです。

**Comment by watemo** [comment]
APIパスを階層で記述していく方法を説明しておりませんでした。

現在、MessageControllerクラスが下記のようになっております。

~~~
@RestController
@RequestMapping("/message")
public class MessageController {

    @GetMapping("/{id}")
    public Message getMessage(@PathVariable String id) {
    //～～～省略~~~
    }

    @GetMapping("/messages")
    public Message index(String messages) {
    //～～～省略~~~
    }

    @PostMapping("/messages")
    public Message postMessage(@PathVariable String messages) {
    //～～～省略~~~
    }
}
~~~

つまり、APIは下記の3つが定義されている状態となります。

- GET http://localhost:8081/message/{id}　…IDを指定してメッセージを取得するメソッド
- GET http://localhost:8081/message/messages　…メッセージを全件取得するメソッド
- POST http://localhost:8081/message/messages　…メッセージを登録するメソッド

RESTful APIは

- 1つのパスで1つのリソースを表す
- メソッドの種類でそのリソースに対しての処理を定義する

という原則があります。
それに則ると今回作成しているメッセージ関連のAPIパスは下記のようになるのが理想的です。

> ■GET http://localhost:8081/message
> メッセージを取得する
> 
> ■POST http://localhost:8081/message
> メッセージを新規登録する
> 
> ■PUT http://localhost:8081/message
> メッセージを更新する
> 
> ■DELETE http://localhost:8081/message
> メッセージを削除する

※PATCHやOPTIONSはあまり自分で実装する機会がありませんので、一旦省略します

「じゃあメッセージを一件だけ登録や削除したい場合は？」と疑問に思われるでしょう。
その場合はメッセージ一件を指定するためのパラメータをパスに含めることで

- 1つのパスで1つのリソースを表す

という原則を満たせるようにします。
修正後のAPIが下記の一覧です。

> ■GET http://localhost:8081/message
> メッセージを全件取得する
> 
> ■GET http://localhost:8081/message/{id}
> メッセージを指定の一件だけ取得する
> 
> ■POST http://localhost:8081/message
> メッセージを新規登録する
> 
> ■PUT http://localhost:8081/message/{id}
> メッセージを指定の一件だけ更新する
> 
> ■DELETE http://localhost:8081/message
> メッセージを全件削除する
> 
> ■DELETE http://localhost:8081/message/{id}
> メッセージを指定の一件だけ削除する

ここで注意してほしいのは新規登録時と更新時の違いです。
処理を想像してほしいのですが、
新規登録時はまだDBにデータが存在しない為、IDを指定することは出来ません。
逆に更新時はDBに登録されているIDをもとに更新するデータを特定しなければ、全データを同じデータで更新してしまうことになります。
なので、新規登録APIにはIDを含めないという形になるのが一般的です。

前置きが長くなりましたが、上記を踏まえた上で現在の定義されているAPIを確認しますと、
ちょっと想定と違う形になっている、というのが分かると思います。

SpringBootの@RequestMappingアノテーションは
クラスに付けたもの　→　メソッドに付けたもの
と繋がっていきますので、MessageControllerクラスに追加した"/message"の部分は
そのクラスに含まれるメソッドに記述する必要はありません。

これらを踏まえたうえで、MessageControllerクラスを修正してみてください。
文章では説明が不足している点もあると思いますので、分からない箇所がありましたら口頭でも説明しますので、遠慮なく質問してください。

**Comment by engineer-achan** [comment]
APIの階層について理解が深まりました。
メッセージの全権取得の時は@GetMappingだけでいいんだぞ！ってことですよね？
しかし今、ControllerClassを修正しているのですがうまくいかないところがあります。
そもそもpath="message"を@RepositoryRestResourceから削除して@RequestMappingで("message")にすると、apiの階層がlocalhost:8081/messageからlocalhost:8081/messagesになってしまうのです。
調べてみたのですがよく原因がわかりません。
なんでmessageを指定しているのにmessagesになってしまうのですか？

もはやここでつまずいてしまっているので今日は前に進めません。。

**Comment by watemo** [comment]
> メッセージの全権取得の時は@GetMappingだけでいいんだぞ！ってことですよね？

今回のAPIパス設計だとその認識でOKです！

> しかし今、ControllerClassを修正しているのですがうまくいかないところがあります。
> そもそもpath="message"を@RepositoryRestResourceから削除して@RequestMappingで("message")にすると、apiの階層がlocalhost:8081/messageからlocalhost:8081/messagesになってしまうのです。

どこかのコードに齟齬があるんだと思います。
確認してみたいのでgitのブランチを新しく作成し、そのブランチに対して
現在のコードを全てコミットしてみてください。

業務であれば「動かないコードをコミットする」という行為は
プログラマがやってはいけないことTOP10に入るほどの重罪ですが、
これは学習用のgitリポジトリなので、レビューのためにもどんどんコミットしましょう。
（git利用方法の勉強にもなりますし）
ただし、その際でもmasterブランチは常に正常に動くコードをコミットするように心がけてください。
実際の業務でもmasterブランチは本番リリース用のコード類を保持する等の
正統なコードが入るリポジトリです。
ここを汚してはいけません。

ブランチの作成方法等が分からない場合は、下記を参照にしてみてください。

・[※Gitコマンド使いません] Githubのブラウザのみでブランチ切ってプルリクするまで
https://qiita.com/sue738/items/7b979c554a03441901c6

・サルでも分かるGit入門　1. ブランチを作成する
https://backlog.com/ja/git-tutorial/stepup/07/


個人的にこのサイトはGit初心者の時にとても助けられましたので、一読をオススメします。
どういう仕組みなのか、こういう時はどう使うのか、がきれいにまとまっています。
・サルでも分かるGit入門
https://backlog.com/ja/git-tutorial/

**Comment by engineer-achan** [comment]
@watemo 了解です！見てみます

**Comment by watemo** [comment]
Issueの本題からずれていたのでこちらに移動しますね。

> 今回はコントローラークラスでは@RequestMapping("messages")は必要なく、idごとの取得のみ@GetMapping("/{id}")と全権取得用の@GetMappingと登録用の@PostMappingを実装すすればいいのかなと思って作っていますが認識あってますか？

まず、現在のプロジェクトはAPIのURLを定義する流れが下記2つあり、
それが混在しているため、理解を妨げる原因になっていると思います。

①コントローラクラス→サービスクラス→リポジトリクラス→MongoDB
②リポジトリクラス→MongoDB

①がSpring Bootを利用したAPIの作成方法、
②がSpring Data RESTを利用したAPIの作成方法になります。

①の場合、コントローラークラスとそのメソッドに付けたアノテーションに応じてAPIが定義されます。
②の場合、リポジトリクラスに付ける@Pathアノテーション、またはリポジトリクラスで利用するモデルクラス名を元にAPIが定義されます。

これら2つは完全に分かれているため、仰るように
`@RequestMapping("messages")`を外しても想定した通りのAPIにはなりません。

すみません。私が変に①の構成を追加したので、混乱してしまったのだと思います。
一旦、どちらかの流れに統一したいと思うのですが、いかがでしょうか？
後程、相談させてください。

**Comment by engineer-achan** [comment]
> まず、現在のプロジェクトはAPIのURLを定義する流れが下記2つあり、
> それが混在しているため、理解を妨げる原因になっていると思います。

これですね
承知いたしました

**Comment by engineer-achan** [comment]
ありがとうございました
