### ISSUE TITLE
gitのコメントは「何をどうするために変更したのか」を1行で記述する

### ISSUE THREAD

**Issue by watemo** [engineer-achan/spring-1022#9]
gitのコメントはコードレビューをする際や、
後程チームメンバーが変更箇所を探す場合にとても大切なものです。

なので、「何をどうするために変更したのか」を簡潔に1行で記述するようにしましょう。

例）

> ユーザ名にバリデーションを追加

> メッセージ新規登録処理のAPIパスを変更

1行で書けない場合は、コミットの粒度が大きすぎる場合がほとんどです。
一度に複数ファイルをまとめてコミットするのではなく、
記述したコメントに関連するファイルだけをコミットしましょう。

どうしても1行で書けない場合は
1行目に概要を記述し、
2行目以降に詳細を記述するのがおすすめです。

また、gitコメントは日本語で書いても問題ありません。
むしろ、実業務では日本語で書くことがほとんどです。
（GitHubにあるOSSなプロジェクトは英語で書いてあることが多いですが、それは世界中の人がコミットするからなのです…）

**Comment by engineer-achan** [comment]
> （GitHubにあるOSSなプロジェクトは英語で書いてあることが多いですが、それは世界中の人がコミットするからなのです…）

勝手に英語が普通なんだと思ってました^^;
何をどうするために変更したのかがわかるような日本語にします

**Comment by engineer-achan** [comment]
こちらがぐちゃぐちゃになってる感があるので新しくリポジトリを作って、Gitの使い方も意識したいと思います。
spring1031にapiの構造がおかしくなる状態をPracticeブランチにコミットしているのでご確認ください

**Comment by watemo** [comment]
原因が判明しました。
@pathアノテーションを外すと、
Repositoryクラスで利用している、Modelクラスの名前を複数形にしたパスを
自動で生成してくれるみたいです。

下記の"Message"部分です。
~~~
public interface MessageRepository extends MongoRepository<Message, String> {
~~~

なので、ここを
~~~
public interface MessageRepository extends MongoRepository<User, String> {
~~~
とすると、APIのパスはhttp://localhost:8080/usersになりました。

**Comment by engineer-achan** [comment]
> 原因が判明しました。
> @pathアノテーションを外すと、
> Repositoryクラスで利用している、Modelクラスの名前を複数形にしたパスを
> 自動で生成してくれるみたいです。

僕も帰ってからいろいろ触っていて気付きました。
今回はコントローラークラスでは@RequestMapping("messages")は必要なく、idごとの取得のみ@GetMapping("/{id}")と全権取得用の@GetMappingと登録用の@PostMappingを実装すすればいいのかなと思って作っていますが認識あってますか？

**Comment by watemo** [comment]
Gitコメントについては双方が認識済みのため、クローズとします。
